### PR TITLE
Json parsing

### PR DESCRIPTION
**Pull request by DuFF14**
Updating JSON parsing fields to match JSON coming from /display

### CODE REVIEW

**Comment by rpavlik** [comment]
Is this all that is needed to work with the v1 schema as formalized?

**Comment by DuFF14** [comment]
It will work with the schema and at least work without errors. It's not parsing everything from the schema, but as far as I can tell Unreal isn't using any more than that. Looks like it used to parse eye location which is not in the current schema, so for the Location of each eye I'm just setting a hard-coded default IPD from the constructor.

**Comment by rpavlik** [comment]
OK, so presumably it doesn't support the other display modes, etc, but it's better than what we currently have, so merging.

**Comment by VRguy** [comment]
We need to create a separate JSON file for user parameters:
- Gender
- Height
- IPD

This is independent of the display parameter file (height does not 
change when I change HMD) but this user JSON file should be parsed by 
the game plugins instead of using default value.

**Pull request merged**
