### PR TITLE
Clarify instruction 4 in Readme.md.

### PR DESCRIPTION
**Pull request by vt5491**
You need to copy the Source directory as well as the Plugins
directory in order to get the plugin to compile under Visual Studio.

### CODE REVIEW

**Comment by kafumanto** [comment]
"Source/OSVRUnreal" is part of the sample project, if you want the plugin in another project you don't have to copy that directory.

**Comment by vt5491** [comment]
I did the following:

1) Downloaded unity project "SciFiHallway" from Unreal Community.
2) Copy the plugins dir to the new project.
3) Copy the source folder too, but rename it to "Source_" (so it won't be found)
4) open the unreal project and create a VSStudio project.
5) Right-click on the SciFiHallway "Solution" and click Build:
osvr_ue4_build_screen

6) Get message
[Severity   Code    Description Project File    Line    Suppression State
Error       Couldn't find target rules file for target 'OSVRUnrealEditor' in rules assembly 'SciFiHallwayModuleRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.   SciFiHallway    C:\Users\Vince\Documents\Unreal Projects\ScifiHallway\Intermediate\ProjectFiles\EXEC    1  
](url)
The original message I got was something like "Couldn't find sources folder".  I don't know why I'm no longer getting that message and this other one instead.
7) Rename "Source_" folder to Source.
8) Redo build on SciFiHallway.
9) get successful build:
1>------ Build started: Project: SciFiHallway, Configuration: Development_Editor x64 ------
1>  Target is up to date.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

I am not a VisualStudio or C++ expert, but it looks to me like it needs the "target" files [OSVRUnreal.Target](url) and [OSVRUnrealEditor.Target](url) in the [Source](url) folder (?).

I guess the question is: Is the source folder associated with the template project or with the plugin?  Empirically, to me it looks like it's associated with the plugin, so it needs to be copied with the plugin.

  I couldn't get my project to compile without copying the source folder.  It's possible you don't need it, but then it must mean I'm doing something wrong, or compiling the wrong "solution", or somehow need to manually define the "OSVRUnreadEditor" target.  But it was just a simple circumention for me to simply copy the Source directory.

**Comment by vt5491** [comment]
I was just reading your comment again.  I wonder if we're talking about the same thing.

> > "Source/OSVRUnreal" is part of the sample project, if you want the plugin in another project you don't have to copy that directory.

Response:
This is true if you've _already built_ the plugin under the sample project.  And I have done this (copied the already built plugin to other projects without copying the "Source" folder). 

But as I read it, these instructions are about how to _build_ the plugin in the context of a project other than the sample project (actually, it also talks about how to build in the context of the model project as well -- it's not always exactly clear about what case it's referring to) .  In this case, I think you need to copy the source as well.  I was able to use the plugin I built using the model project in two other projects by simply coping the plugins directory as you say.  But then I hit the "SciFiHallway" project and the default Plugin wasn't working.   So I decided to build it in the context of the new project, and thus I had to copy the Source folder.

So maybe we're just talking about two separate things?  Would you ever need to build the plugin in a project other than the model project?

**Comment by JeroMiya** [comment]
The part that needs clarification is the fact that your project needs to have at least one C++ game module, which is normally contained under the /Source directory of the project. If your project is a pure-blueprint project (like many of the samples) then you need to create a dummy C++ module. The easiest way to do that is to copy the one from OSVRUnreal and rename everything to match your project's name (although it may work without renaming, as @vt5491 seems to be able to do).

This is because Unreal's build system doesn't generate a visual studio project unless there is at least one C++ module, even when there are local game plugins that need to be compiled. In this case, I haven't tested it, but it might still work if you build the plugin first from the OSVRUnreal project and copy it and the binaries to the new project. If so, maybe we should change the instructions to have people build OSVRUnreal first and then copy?

**Comment by kafumanto** [comment]
Yep, but the easiest way is to add a new C++ file from the Content Browser. UE4 will automatically setup everything as needed.

**Comment by vt5491** [comment]
Ultimately, I don't think any of this matters until you can provide a pre-compiled binary that just works.  I'm not complaining here, just making an observation.  I actually don't understand why this is such a difficult thing to do.  You can't reasonably expect people to have to watch a fifteen minute video, and do a 10-step build process, that involves compiling raw source, and renaming files etc just to get a "simple" plugin to work.  

While, after a great deal of effort, I've been able to get some projects to actually build, I've never been able to get a build to _actually run_  (it crashes my ue4 editor).

Especially since one of the selling points of using unreal is Blueprint, which allows people who don't even want to use a _scripting_ language to be able to "program" as necessary e.g. for "creatives" who are not technical.  There's little chance they'll even _attempt_ to build the plugin.

The unity5 OSVR plugin is a relative breeze compared to this.  They have pre-compiled prefabs that you just import into your assets folder, and then drag and drop two assets into your scene.

I'm sure you're well aware of this.  Just saying it doesn't really make sense to try to make the current procedure more understandable.  Just put all your efforts into providing a turnkey binary as soon as possible.  

Otherwise, I would suggest this plugin is doomed for failure.

I'm not trying to be negative here.  I appreciate the hard work that has been done on this plugin.  And I have gotten it to work by using [https://forums.unrealengine.com/showthread.php?97206-Precompiled-OSVR-Plugins-and-Tutorials](these pre-compile binaries).  It's just pretty frustrating to have spent so much time, and not be able to get it work (in the general at least), esp. given that It's not clear why a binary cannot be provided when there _is_ one for Unity.

**Comment by JeroMiya** [comment]
There should be a CI generated binary available relatively soon. I have been preparing a major release which has taken up all my time (stay tuned!).

Please note that the plugin already works as a globally installed engine plugin, which removes the requirement of making a dummy C++ module or copy the plugin into each project. I haven't updated the readme because in my testing it only worked with a custom engine build and I would like to get the binary working in the prepackaged engine release as well.

**Comment by vt5491** [comment]
Excellent.  This is great news.

Can't wait for the new release.

**Pull request closed without merging**
